services:
  - type: web
    name: unisole-api
    env: docker
    dockerfilePath: ./api/Dockerfile
    autoDeploy: true
    envVars:
      - key: API_KEY
        value: unisole-test-key
      - key: NEWSAPI_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant

  - type: web
    name: unisole-streamlit
    env: docker
    dockerfilePath: ./streamlit/Dockerfile
    autoDeploy: true
    envVars:
      - key: API_BASE_URL
        value: https://unisole-api.onrender.com
      - key: API_KEY
        value: unisole-test-key
      - key: NEWSAPI_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GROQ_MODEL
        value: llama-3.1-8b-instant
      - key: LANGCHAIN_TRACING_V2
        value: "false"
